project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Li Jingwei"
  site-url: https://JingweiLiecon.github.io
  favicon: images/site-logo.png

  
  page-footer:
    left: |
      &nbsp;
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#003DA5"
    search: true
    right: 
      - text: "MAIN"
        href: index.qmd
      - text: "CV"
        href: Li Jingwei - SMU.pdf
      - text: "RESEARCH"
        href: research.qmd
      - text: "TEACHING"
        href: teaching.qmd
      - text: "OTHERS"
        href: others.qmd

format:
  html:
    theme: styles.scss
    toc: false        