project:
  type: website
  resources:
    - google462d01e8d4e8a695.html
  output-dir: docs
  
website:
  page-navigation: true
  title: "Li Jingwei"
  site-url: https://JingweiLiecon.github.io
  favicon: images/site-logo.png

  
  page-footer:
    left: |
    
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#FFFFFF"
    foreground: "#555555"
    search: false

    left: 
      - text: "CV"
        href: cv.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      

format:
  html:
    theme: styles.scss
    toc: false
    include-in-header:
      text: |
        <meta name="google-site-verification" content="hbBIZGbZ5ZvrQZpagCLS-PWdkx6w-QN6ccPyNFLt13M" />      